#if !canImport(ObjectiveC)
import XCTest

extension BitPackingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BitPackingTests = [
        ("testMultiByte8To3", testMultiByte8To3),
        ("testPackingPerformance", testPackingPerformance),
        ("testSingleByte8To2", testSingleByte8To2),
        ("testUnpackingPerformance", testUnpackingPerformance),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BitPackingTests.__allTests__BitPackingTests),
    ]
}
#endif
