#if !canImport(ObjectiveC)
import XCTest

extension BitPackingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BitPackingTests = [
        ("testMultiByte8To3", testMultiByte8To3),
        ("testPackingPerformance", testPackingPerformance),
        ("testSingleByte8To2", testSingleByte8To2),
        ("testUnpackingPerformance", testUnpackingPerformance),
    ]
}

extension StreamCodingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StreamCodingTests = [
        ("testStreamDecoder", testStreamDecoder),
        ("testStreamEncoder", testStreamEncoder),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BitPackingTests.__allTests__BitPackingTests),
        testCase(StreamCodingTests.__allTests__StreamCodingTests),
    ]
}
#endif
